### ISSUE TITLE
Build android failed on Windows

### ISSUE THREAD

**Issue by ylz-at** [KhronosGroup/Vulkan-Samples#480]
`./gradlew app:assembleRelease` outputs,
```
> Build command failed.
  Error while executing process C:\Users\xxx\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe with arguments {-C C:\Users\xxx\AndroidStudioProjects\KhronosGroupVulkan-Samples\build\android_gradle\app\buil
d-native\RelWithDebInfo\2h311d26\arm64-v8a spirv-cross vulkan_samples}
  ninja: Entering directory `C:\Users\xxx\AndroidStudioProjects\KhronosGroupVulkan-Samples\build\android_gradle\app\build-native\RelWithDebInfo\2h311d26\arm64-v8a'

  [0/2] Re-checking globbed directories...
  ninja: build stopped: .

  ninja: error: mkdir(third_party/CMakeFiles/native_app_glue.dir/C_/Users/xxx/AppData/Local/Android/Sdk/ndk/21.4.7075529/sources): No such file or directory
```

cmake version: 3.18
ndk version: 21.4.7075529

**Comment by SaschaWillems** [comment]
Hard to help with so little details. The error hints at a missing file in either a submodule or the NDK. So is the Android NKD properly installed, and did you clone the repo with submodules?

**Comment by marty-johnson59** [comment]
Hi @ylz-at, let us know if you can provide more details.  I'll close this shortly if not - we can re-open later if more info can be provided.  Thanks!

**Comment by marty-johnson59** [comment]
Oops, closed too soon.  But we'll likely close this in a week or 2 without further info.

**Comment by ylz-at** [comment]
@SaschaWillems Android SDK and NDK are correctly installed with AndroidStudio, and I can compile other android-native projects, such as https://github.com/SaschaWillems/Vulkan, just fine. And the repo is cloned with submodules.

I was trying to build a CI pipeline on windows to demonstrate this problem, but it takes hours to run...weird.
https://github.com/ylz-at/Vulkan-Samples/runs/7421535652?check_suite_focus=true

The pipeline is simple checkout and gradlew assemble.
```yml
name: Build Project

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  build_android:
    name: "Build Android"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: "Run generate script"
        run: ./bldsys/scripts/generate_android_gradle.bat
#      - name: "Explicitly setup SDK path with local.properties."
#        run: |
#          echo "sdk.dir=/usr/local/android-sdk" > build/android_gradle/local.properties
#          echo "ndk.dir=/usr/local/android-ndk" >> build/android_gradle/local.properties
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: "Build Android using gradlew."
        working-directory: build/android_gradle
        run: ./gradlew app:assembleRelease
```
